import React, { useEffect, useState } from 'react';
import type { Grade, Review, Settings, Unit } from '../domain/models';
import type { Practice } from '../domain/enrichment';
import { enrichmentData, localDay, savePractice, completePractice } from '../data/enrichment';
import { db } from '../data/db';
import { settings, saveSettings } from '../data/repository';
import { getProvider } from '../ai/factory';
import { errorProfile } from '../learning/errors';
import { errorLabels } from '../domain/error-categories';
import { grammarTopics, grammarTopic } from '../learning/taxonomy';
import { familiarity, loadFrequency } from '../learning/frequency';
import { generateWeekly, optimizeSchedule, previousWeek, prepareTargeted } from '../learning/maintenance';
import type { Run } from './learning-tools';

type Extra = Awaited<ReturnType<typeof enrichmentData>>;
const empty: Extra = { assessments: [], usage: [], practices: [], weekly: [], dictionary: [], optimization: [] };
export function Insights({ units, reviews, config, busy, run }: { units: Unit[]; reviews: Review[]; config: Settings; busy: boolean; run: Run }) {
  const [data, setData] = useState<Extra>(empty); const [ranks, setRanks] = useState(new Map<string, number>()); const [selected, setSelected] = useState<string>();
  const reload = async () => setData(await enrichmentData());
  useEffect(() => { void reload(); void loadFrequency().then(setRanks).catch(() => undefined); }, [units, reviews, busy]);
  useEffect(() => { void run(prepareTargeted); }, []);
  const profile = errorProfile(data.assessments); const day = localDay();
  const today = data.usage.filter(u => u.day === day); const month = data.usage.filter(u => u.month === day.slice(0, 7));
  const lastOptimization = data.optimization.slice().sort((a, b) => b.at - a.at)[0];
  const week = previousWeek(); const learned = new Set(reviews.filter(r => r.at >= week.start && r.at < week.end).map(r => r.unitId));
  const covered = new Set(data.weekly.filter(w => w.week === week.key).flatMap(w => w.coverage.map(c => c.unitId)));
  const practice = data.practices.find(p => p.id === selected) ?? data.practices.find(p => !p.completedAt);
  const unit = units.find(u => u.id === practice?.unitId);
  async function targeted() {
    const top = profile[0]; if (!top) return;
    const target = units.find(u => top.units.has(u.id) && !u.reportedIssue); if (!target) throw new Error('Cần một mục đã kiểm tra nội dung để luyện lỗi này.');
    const drill = await (await getProvider()).targeted(target.knowledge, top.examples);
    const saved = await savePractice(target.id, drill, target.updatedAt); setSelected(saved.id); await reload();
  }
  return <><div className="page-heading"><div><div className="eyebrow">HIỂU CÁCH MÌNH ĐANG HỌC</div><h1>Nhìn rõ điều cần luyện.</h1><p>Lỗi trong bài viết, chi tiết bỏ sót khi nghe và những vùng kiến thức bạn chưa đi qua.</p></div></div>
    <section className="panel"><div className="section-heading"><h2>Hồ sơ lỗi của bạn</h2><button disabled={busy || !profile.length} onClick={() => void run(targeted)}>Tạo bài nhắm vào lỗi thường gặp nhất</button></div><p className="muted">{data.assessments.length} bài đã chấm · Lưu ngay sau khi chấm, kể cả khi bạn chưa chọn mức nhớ. Luyện bổ sung không tự đổi lịch FSRS.</p>{!profile.length && <p>Chưa có lỗi được ghi nhận. Viết thử hoặc nghe chép chính tả ở phần Ôn tập.</p>}{profile.map(item => <details key={item.category} className="error-profile-row"><summary><strong>{errorLabels[item.category]}</strong><span>{item.recent} lỗi / 30 ngày · {item.count} tổng cộng · {item.units.size} mục</span></summary>{item.examples.map((error, i) => <div key={i} className="error-detail"><p><del>{error.original || '∅'}</del> → <strong>{error.correction || '∅'}</strong></p><p>{error.reasonVi}</p>{error.l1NoteVi && <p className="hint-box">{error.l1NoteVi}</p>}</div>)}</details>)}</section>
    {practice && unit && <TargetedPractice key={practice.id} practice={practice} unit={unit} onDone={reload} run={run} busy={busy}/>}
    <section className="panel"><h2>Bản đồ ngữ pháp</h2><p className="muted">Màu dựa trên tối thiểu 5 lượt ôn cách nhau ≥ 1 ngày trong 90 ngày gần đây. “Chưa gặp” chỉ nói về kho của bạn; không phải kết luận bạn chưa biết.</p><div className="grammar-map">{[...new Set(grammarTopics.map(t => t.parent))].map(parent => <div key={parent}><h3>{parent}</h3>{grammarTopics.filter(t => t.parent === parent).map(topic => {
      const members = units.filter(u => grammarTopic(u.knowledge)?.id === topic.id); const ids = new Set(members.map(u => u.id));
      const history = reviews.filter(r => ids.has(r.unitId) && r.at >= Date.now() - 90 * 86400000 && r.prior.state === 2 && r.prior.last_review && r.at - r.prior.last_review >= 86400000);
      const rate = history.length ? history.filter(r => r.rating > 1 && !r.assisted).length / history.length : 0;
      const status = !members.length ? 'unseen' : history.length < 5 ? 'learning' : rate < 0.8 ? 'weak' : rate >= config.retention ? 'strong' : 'learning';
      return <div className={`topic topic-${status}`} key={topic.id}><strong>{topic.name}</strong><span>{!members.length ? 'Chưa gặp' : `${members.length} mục · ${history.length < 5 ? 'Đang tích lũy lượt ôn' : `${Math.round(rate * 100)}% nhớ · ${history.length} lượt`}`}</span></div>;
    })}</div>)}</div><p className="muted">Chưa phân loại: {units.filter(u => u.knowledge.kind === 'grammar' && !grammarTopic(u.knowledge)).length} mục. Cây chủ đề hiện là bộ khung biên tập, không bao quát mọi cấu trúc tiếng Anh.</p></section>
    <div className="settings-grid"><section className="panel"><h2>Độ khó của kho học liệu</h2><p>Trình độ tự chọn: <strong>{config.learnerLevel}</strong></p><div className="level-chart">{['A1', 'A2', 'B1', 'B2', 'C1', 'C2'].map(level => { const count = units.filter(u => familiarity(u.knowledge, ranks).level === level).length; return <div key={level}><span>{level}</span><meter min={0} max={Math.max(1, units.length)} value={count}/><strong>{count}</strong></div>; })}</div><p className="muted">Ước lượng từ hạng tần suất từ thành phần và cây ngữ pháp, không phải chứng nhận CEFR. Dữ liệu OpenSubtitles thiên về lời nói/phim; cụm chuyên ngành có thể bị đánh giá thấp. Chưa xác định: {units.filter(u => !familiarity(u.knowledge, ranks).level).length} mục.</p><p>{units.reduce((n, u) => n + u.encounters, 0)} lần gặp tự nhiên đã ghi nhận. Đây là mức tiếp xúc bổ sung, không được tự chấm thành nhớ đúng.</p></section>
    <section className="panel"><h2>Sử dụng AI</h2><p>Hôm nay <strong>{today.length} / {config.dailyApiLimit}</strong> request</p><progress max={config.dailyApiLimit} value={today.length}/><p>Tháng này <strong>{month.length} / {config.monthlyApiLimit}</strong> request</p><progress max={config.monthlyApiLimit} value={month.length}/>{(today.length >= config.dailyApiLimit * 0.8 || month.length >= config.monthlyApiLimit * 0.8) && <p className="hint-box" role="status">Sắp đạt hạn mức bạn đặt. Để phân tích sau hoặc điều chỉnh hạn mức trong Cài đặt.</p>}<p className="muted">{month.reduce((n, u) => n + u.tokens, 0).toLocaleString('vi-VN')} token do API báo · {month.filter(u => u.status === 'failed').length} lần lỗi. Request chưa có kết quả vẫn tính vào giới hạn. Không quy đổi sang tiền vì giá phụ thuộc model và tài khoản.</p><details><summary>Các lần gọi gần đây</summary>{data.usage.slice().sort((a, b) => b.at - a.at).slice(0, 20).map(u => <p className="muted" key={u.id}>{new Date(u.at).toLocaleString('vi-VN')} · {u.model} · {{ analysis: 'Phân tích', transcript: 'Sửa phụ đề', grading: 'Chấm viết', explanation: 'Giải thích lại', targeted: 'Luyện lỗi', weekly: 'Tổng hợp tuần' }[u.task]} · {{ started: 'Đã gửi', success: 'Hoàn tất', failed: 'Lỗi' }[u.status]}</p>)}</details></section></div>
    <section className="panel"><div className="section-heading"><h2>Đoạn đọc nối lại một tuần</h2><button disabled={busy || !learned.size || covered.size >= learned.size} onClick={() => void run(generateWeekly, 'Đã lưu phần tổng hợp. Nếu tuần có nhiều mục, tiếp tục để tạo phần còn lại.')}>Tạo / tiếp tục tổng hợp tuần trước</button></div><p>Tuần bắt đầu {week.key}: đã đưa {covered.size}/{learned.size} kiến thức từng ôn vào các đoạn ngắn.</p><p className="muted">Mỗi đoạn tối đa 8 mục để câu chuyện còn tự nhiên. Đọc liền mạch bổ sung ngữ cảnh; tự viết và ôn đến hạn vẫn là cách kiểm tra bạn có nhớ.</p>{data.weekly.slice().sort((a, b) => b.createdAt - a.createdAt).slice(0, 20).map(w => <details key={w.id}><summary>{w.titleVi} · Tuần {w.week}</summary><p className="english weekly-text">{w.textEn}</p><details><summary>Xem nghĩa tiếng Việt</summary><p>{w.meaningVi}</p></details><div className="coverage-list">{w.coverage.map(c => <p key={c.unitId}><strong>{units.find(u => u.id === c.unitId)?.knowledge.name}</strong>: <q>{c.quote}</q></p>)}</div></details>)}</section>
    <section className="panel"><div className="section-heading"><h2>Lịch ôn hợp với trí nhớ của bạn</h2><button disabled={busy || reviews.length < 1000} onClick={() => void run(() => optimizeSchedule(true), 'Đã kiểm tra hiệu chỉnh tham số.')}>Kiểm tra hiệu chỉnh FSRS</button></div><p>{reviews.length} / 1.000 lượt ôn để bắt đầu kiểm tra.</p><p className="muted">Tiến trình riêng thử 6 tham số về độ bền trí nhớ, kiểm định trên 20% lịch sử mới nhất chưa dùng để chọn tham số. Chỉ áp dụng nếu sai số giảm đủ. Đây là hiệu chỉnh giới hạn, chưa phải bộ tối ưu đầy đủ 21 tham số của FSRS.</p>{lastOptimization && <><p>{lastOptimization.noteVi}</p><p className="muted">{lastOptimization.trainingSamples} mẫu huấn luyện · {lastOptimization.validationSamples} mẫu kiểm định · Sai số {lastOptimization.baselineLoss.toFixed(4)} → {lastOptimization.candidateLoss.toFixed(4)}</p>{lastOptimization.applied && config.fsrsWeights && <button disabled={busy} onClick={() => void run(async () => { await saveSettings({ ...await settings(), fsrsWeights: lastOptimization.previousWeights, optimizationEnabled: false }); await (await db).put('optimization', { ...lastOptimization, applied: false, noteVi: 'Bạn đã hoàn tác về bộ tham số trước và tắt tự hiệu chỉnh.' }); }, 'Đã hoàn tác tham số. Lịch đến hạn hiện tại được giữ nguyên.')}>Hoàn tác tham số & tắt tự hiệu chỉnh</button>}</>}</section>
  </>;
}
function TargetedPractice({ practice, unit, run, busy, onDone }: { practice: Practice; unit: Unit; run: Run; busy: boolean; onDone: () => Promise<void> }) {
  const [answer, setAnswer] = useState(''); const [grade, setGrade] = useState<Grade>();
  return <section className="panel targeted-practice"><span className="eyebrow">LUYỆN RIÊNG · {errorLabels[practice.category]}</span><h2>{practice.instructionVi}</h2>{!grade && !practice.completedAt && <><label>Câu trả lời tiếng Anh<textarea value={answer} maxLength={8000} onChange={e => setAnswer(e.target.value)} disabled={busy}/></label><button className="primary" disabled={busy || !answer.trim()} onClick={() => void run(async () => { const result = await (await getProvider()).grade(unit.knowledge, practice.instructionVi, answer); await completePractice(practice, answer, result); setGrade(result); await onDone(); })}>Chấm & lưu vào hồ sơ lỗi</button></>}{(grade || practice.completedAt) && <><p>{grade?.feedbackVi}</p>{grade?.errors.map((e, i) => <div className="error-detail" key={i}><p><del>{e.original}</del> → <strong>{e.correction}</strong></p><p>{e.reasonVi}</p>{e.l1NoteVi && <p className="hint-box">{e.l1NoteVi}</p>}</div>)}<p className="english">{grade?.correctedEn ?? practice.answerEn}</p><p>{practice.explanationVi}</p></>}</section>;
}
