import React, { useEffect, useState } from 'react';
import type { Capture, Settings, Unit } from '../domain/models';
import type { DictionaryEntry } from '../domain/enrichment';
import { db } from '../data/db';
import { reviseUnit } from '../data/repository';
import { getProvider } from '../ai/factory';
import { lookupDictionary } from '../ai/dictionary';
import { send } from '../shared/client';
import { timestamp } from '../video/captions';
import { localDay } from '../data/enrichment';
export type Run = (action: () => Promise<unknown>, success?: string) => Promise<void>;
export function BudgetNotice({ config }: { config: Settings }) {
  const [counts, setCounts] = useState({ day: 0, month: 0 });
  useEffect(() => { let active = true; void db.then(async d => { const date = localDay(); const [day, month] = await Promise.all([d.countFromIndex('usage', 'day', date), d.countFromIndex('usage', 'month', date.slice(0, 7))]); if (active) setCounts({ day, month }); }).catch(() => undefined); return () => { active = false; }; }, [config]);
  if (counts.day < config.dailyApiLimit * 0.8 && counts.month < config.monthlyApiLimit * 0.8) return null;
  return <div className="notice" role="status"><span>{counts.day >= config.dailyApiLimit || counts.month >= config.monthlyApiLimit ? 'Đã đạt' : 'Sắp đạt'} hạn mức AI: {counts.day}/{config.dailyApiLimit} hôm nay · {counts.month}/{config.monthlyApiLimit} tháng này.</span><a href="#insights">Xem lượng sử dụng ↗</a></div>;
}

export function OriginalAudio({ capture, blind = false }: { capture: Capture; blind?: boolean }) {
  const [playing, setPlaying] = useState(0); const [error, setError] = useState(''); const clip = capture.source.video;
  if (!clip) return null;
  return <div className="original-audio"><div className="actions left"><button onClick={() => setPlaying(n => n + 1)}>▶ {playing ? 'Phát lại' : 'Nghe'} đoạn gốc · {timestamp(clip.start)}–{timestamp(clip.end)}</button><button onClick={() => void send({ type: 'play-source', video: clip, blind }).catch(e => setError(String(e)))}>Mở đoạn trên YouTube ↗</button>{playing > 0 && <button onClick={() => setPlaying(0)}>Đóng trình phát</button>}</div>{playing > 0 && <iframe key={playing} title="Đoạn video gốc để luyện nghe" width="100%" height="230" referrerPolicy="strict-origin-when-cross-origin" allow="autoplay; encrypted-media; fullscreen" src={`https://www.youtube-nocookie.com/embed/${clip.videoId}?start=${Math.floor(clip.start)}&end=${Math.ceil(clip.end)}&autoplay=1&playsinline=1&cc_load_policy=${blind ? 0 : 1}&cc_lang_pref=en&md-review=1&md-blind=${blind ? 1 : 0}`}/>}<p className="muted">{clip.timing === 'track' ? 'Mốc từ track phụ đề.' : 'Mốc ước lượng từ phụ đề hiển thị.'} Trình phát nhúng làm tròn tới giây. Nếu video chặn nhúng hoặc báo lỗi 153, mở đoạn trên YouTube để phát và dừng theo mốc đã lưu.{blind && ' Tắt CC trong trình phát trước khi nghe chép chính tả.'}</p>{error && <p role="status">{error}</p>}</div>;
}
export function TranscriptCheck({ capture, run, busy }: { capture: Capture; run: Run; busy: boolean }) {
  const [approvedLocal, setApprovedLocal] = useState(!!capture.transcriptApproved);
  const repair = capture.analysis?.transcript;
  if (!repair) return null;
  return <details className="transcript-check" open={repair.uncertain && !capture.transcriptApproved}><summary>Kiểm tra bản phục hồi phụ đề {repair.uncertain ? '· Cần nghe lại' : ''}</summary><p className="english">{repair.textEn}</p><p>{repair.warningVi}</p>{repair.changes.map((change, i) => <p key={i}><del>{change.original}</del> → <strong>{change.corrected}</strong><br/>{change.reasonVi}</p>)}<p className="muted">AI chỉ đọc transcript, chưa nghe audio. Câu gốc và thời gian vẫn được giữ riêng.</p>{repair.uncertain && <label className="checkbox-label"><input type="checkbox" checked={approvedLocal} disabled={busy || capture.unitsCreated} onChange={e => { const approved = e.target.checked; setApprovedLocal(approved); void run(async () => { const tx = (await db).transaction('captures', 'readwrite'); const item = await tx.store.get(capture.id); if (item) await tx.store.put({ ...item, transcriptApproved: approved }); await tx.done; }); }}/>Tôi đã nghe lại và xác nhận câu phục hồi đúng</label>}</details>;
}
export function UnitTools({ unit, busy = false, run }: { unit: Unit; busy?: boolean; run: Run }) {
  const [issue, setIssue] = useState(unit.reportedIssue ?? ''); const [dictionary, setDictionary] = useState<DictionaryEntry>();
  const [word, setWord] = useState(unit.knowledge.kind === 'phrase' ? unit.knowledge.form : unit.knowledge.evidence.split(/\s+/)[0] ?? '');
  return <details className="unit-tools"><summary>Kiểm tra nội dung & ưu tiên học {unit.reportedIssue ? '· Đã báo cần sửa' : ''}</summary><div className="actions left"><button disabled={busy} onClick={() => void run(async () => { await reviseUnit(unit.id, { alternativeVi: await (await getProvider()).explain(unit.knowledge) }); }, 'Đã lưu cách giải thích khác.')}>Giải thích theo cách khác</button><label>Ưu tiên mục mới<select value={unit.priority ?? 'auto'} disabled={busy} onChange={e => void run(() => reviseUnit(unit.id, { priority: e.target.value as 'auto' | 'high' | 'low' }))}><option value="auto">Theo tần suất</option><option value="high">Ưu tiên cao</option><option value="low">Để học sau</option></select></label></div>{unit.alternativeVi && <p>{unit.alternativeVi}</p>}<label>Nội dung sai / điều cần kiểm tra<textarea maxLength={8000} value={issue} onChange={e => setIssue(e.target.value)} placeholder="Ví dụ: tên cấu trúc không khớp câu gốc…"/></label><div className="actions left"><button disabled={busy || !issue.trim()} onClick={() => void run(() => reviseUnit(unit.id, { reportedIssue: issue, suspended: true }), 'Đã lưu báo lỗi trên máy và tạm dừng mục để tránh học sai.')}>Lưu báo lỗi & tạm dừng</button>{unit.reportedIssue && <button disabled={busy} onClick={() => void run(() => reviseUnit(unit.id, { reportedIssue: '', suspended: false }), 'Đã đánh dấu kiểm tra xong.')}>Đã kiểm tra · Ôn lại</button>}</div><label>Từ / cụm cần đối chiếu từ điển<input value={word} maxLength={100} onChange={e => setWord(e.target.value)}/></label><button disabled={busy || !word.trim()} onClick={() => void run(async () => setDictionary(await lookupDictionary(word)))}>Tra nguồn từ điển</button><p className="muted">Tra cứu gửi từ/cụm tới Dictionary API, không gửi câu trả lời của bạn. Đây là định nghĩa tiếng Anh từ nguồn từ điển; không phải xác nhận tự động cho phân tích ngữ pháp.</p>{dictionary && <div className="dictionary-result">{dictionary.status === 'not_found' ? <p>Nguồn này chưa có mục tương ứng. Điều đó không chứng minh cụm từ không tồn tại.</p> : <><p><strong>{dictionary.word}</strong> {dictionary.phonetic}</p>{dictionary.definitions.map((d, i) => <p key={i}><small>{d.partOfSpeech}</small> · {d.definition}{d.example && <><br/><em>{d.example}</em></>}</p>)}{dictionary.sources.map(url => <a key={url} href={url} target="_blank" rel="noopener noreferrer">Nguồn định nghĩa ↗ </a>)}<p className="muted">{dictionary.license}</p></>}</div>}</details>;
}
export function AdvancedSettings({ draft, set }: { draft: Settings; set: <K extends keyof Settings>(key: K, value: Settings[K]) => void }) {
  return <section className="panel"><h2>Cá nhân hóa việc học</h2><label>Model mạnh hơn · Chấm viết, luyện lỗi và giải thích lại<input value={draft.strongModel} onChange={e => set('strongModel', e.target.value)}/></label><label>Hạn mức request AI mỗi ngày<input type="number" min="1" max="10000" value={draft.dailyApiLimit} onChange={e => set('dailyApiLimit', Number(e.target.value))}/></label><label>Hạn mức request AI mỗi tháng<input type="number" min="1" max="100000" value={draft.monthlyApiLimit} onChange={e => set('monthlyApiLimit', Number(e.target.value))}/></label><p className="muted">Đếm mọi lần thử, kể cả lỗi; kết quả lấy từ cache không tính. Đây là giới hạn request trên máy, không phải hạn mức chi phí tài khoản Google.</p><label>Trình độ bạn tự đánh giá<select value={draft.learnerLevel} onChange={e => set('learnerLevel', e.target.value as Settings['learnerLevel'])}>{['A1', 'A2', 'B1', 'B2', 'C1', 'C2'].map(level => <option key={level}>{level}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={draft.inflectionMatching} onChange={e => set('inflectionMatching', e.target.checked)}/>Nhận thêm dạng biến đổi phổ biến khi bật đánh dấu</label><p className="muted">Dùng bảng biến thể giới hạn, cùng nghĩa cần kiểm tra theo ngữ cảnh. Lần gặp tự nhiên được thống kê riêng; không tự cộng thành một lượt nhớ đúng.</p><label className="checkbox-label"><input type="checkbox" checked={draft.optimizationEnabled} onChange={e => set('optimizationEnabled', e.target.checked)}/>Tự hiệu chỉnh FSRS khi đủ lịch sử (từ 1.000 lượt)</label><label className="checkbox-label"><input type="checkbox" checked={draft.targetedAutomatic} onChange={e => set('targetedAutomatic', e.target.checked)}/>Tự chuẩn bị bài luyện khi cùng nhóm lỗi xuất hiện ít nhất 3 lần</label><p className="muted">Tối đa một bài mới/ngày khi mở góc học hoặc hồ sơ; cần API key, còn quota và không có bài đang chờ làm.</p><label className="checkbox-label"><input type="checkbox" checked={draft.weeklyAutomatic} onChange={e => set('weeklyAutomatic', e.target.checked)}/>Tự tạo bài đọc tổng hợp tuần trước khi mở góc học</label><p className="muted">Tùy chọn này gửi các kiến thức đã ôn trong tuần tới Gemini. Mỗi đoạn tối đa 8 mục; mỗi lần mở tạo tối đa 4 đoạn, lần sau tiếp tục phần còn lại.</p></section>;
}
